
    var events = [
  {'Date': new Date(2018, 5, 28), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June28').modal('show');}},
  {'Date': new Date(2018, 5, 27), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June27').modal('show');}},
  {'Date': new Date(2018, 5, 26), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June26').modal('show');}},
  {'Date': new Date(2018, 5, 25), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June25').modal('show');}},
  {'Date': new Date(2018, 5, 24), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June24').modal('show');}},
  {'Date': new Date(2018, 5, 23), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June23').modal('show');}},
  {'Date': new Date(2018, 5, 22), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June22').modal('show');}},
  {'Date': new Date(2018, 5, 21), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June21').modal('show');}},
  {'Date': new Date(2018, 5, 19), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June19').modal('show');}},
  {'Date': new Date(2018, 5, 18), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June18').modal('show');}},
  {'Date': new Date(2018, 5, 17), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June17').modal('show');}},
  {'Date': new Date(2018, 5, 16), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June16').modal('show');}},
  {'Date': new Date(2018, 5, 15), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June15').modal('show');}},
  {'Date': new Date(2018, 5, 14), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June14').modal('show');}},
  {'Date': new Date(2018, 5, 12), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June12').modal('show');}},
  {'Date': new Date(2018, 5, 11), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June11').modal('show');}},
  {'Date': new Date(2018, 5, 10), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June10').modal('show');}},
  {'Date': new Date(2018, 5, 09), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June09').modal('show');}},
  {'Date': new Date(2018, 5, 08), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June08').modal('show');}},
  {'Date': new Date(2018, 5, 05), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June05').modal('show');}},
  {'Date': new Date(2018, 5, 04), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June04').modal('show');}},
  {'Date': new Date(2018, 5, 03), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June03').modal('show');}},
  {'Date': new Date(2018, 5, 02), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June02').modal('show');}},
  {'Date': new Date(2018, 5, 01), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018June01').modal('show');}},

  {'Date': new Date(2018, 4, 31), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May31').modal('show');}},
  {'Date': new Date(2018, 4, 30), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May30').modal('show');}},
  {'Date': new Date(2018, 4, 28), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May28').modal('show');}},
  {'Date': new Date(2018, 4, 27), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May27').modal('show');}},
  {'Date': new Date(2018, 4, 26), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May26').modal('show');}},
  {'Date': new Date(2018, 4, 25), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May25').modal('show');}},
  {'Date': new Date(2018, 4, 22), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May22').modal('show');}},
  {'Date': new Date(2018, 4, 21), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May21').modal('show');}},
  {'Date': new Date(2018, 4, 20), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May20').modal('show');}},
  {'Date': new Date(2018, 4, 19), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May19').modal('show');}},
  {'Date': new Date(2018, 4, 18), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May18').modal('show');}},
  {'Date': new Date(2018, 4, 17), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May17').modal('show');}},
  {'Date': new Date(2018, 4, 16), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May16').modal('show');}},
  {'Date': new Date(2018, 4, 15), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May15').modal('show');}},
  {'Date': new Date(2018, 4, 14), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May14').modal('show');}},
  {'Date': new Date(2018, 4, 13), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May13').modal('show');}},
  {'Date': new Date(2018, 4, 12), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May12').modal('show');}},
  {'Date': new Date(2018, 4, 10), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May10').modal('show');}},
  {'Date': new Date(2018, 4, 09), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May09').modal('show');}},  
  {'Date': new Date(2018, 4, 08), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May08').modal('show');}},
  {'Date': new Date(2018, 4, 07), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May07').modal('show');}},
  {'Date': new Date(2018, 4, 06), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May06').modal('show');}},
  {'Date': new Date(2018, 4, 05), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May05').modal('show');}},
  {'Date': new Date(2018, 4, 04), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May04').modal('show');}},
  {'Date': new Date(2018, 4, 03), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May03').modal('show');}},
  {'Date': new Date(2018, 4, 02), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May02').modal('show');}},
  {'Date': new Date(2018, 4, 01), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018May01').modal('show');}},

  {'Date': new Date(2018, 3, 29), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April29').modal('show');}},
  {'Date': new Date(2018, 3, 28), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April28').modal('show');}},
  {'Date': new Date(2018, 3, 27), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April27').modal('show');}},
  {'Date': new Date(2018, 3, 26), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April26').modal('show');}},
  {'Date': new Date(2018, 3, 24), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April24').modal('show');}},
  {'Date': new Date(2018, 3, 23), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April23').modal('show');}},
  {'Date': new Date(2018, 3, 22), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April22').modal('show');}},
  {'Date': new Date(2018, 3, 21), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April21').modal('show');}},
  {'Date': new Date(2018, 3, 20), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April20').modal('show');}},
  {'Date': new Date(2018, 3, 19), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April19').modal('show');}},
  {'Date': new Date(2018, 3, 18), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April18').modal('show');}},
  {'Date': new Date(2018, 3, 17), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April17').modal('show');}},
  {'Date': new Date(2018, 3, 16), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April16').modal('show');}},
  {'Date': new Date(2018, 3, 15), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April15').modal('show');}},
  {'Date': new Date(2018, 3, 14), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April14').modal('show');}},
  {'Date': new Date(2018, 3, 13), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April13').modal('show');}},
  {'Date': new Date(2018, 3, 11), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April11').modal('show');}},
  {'Date': new Date(2018, 3, 10), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April10').modal('show');}},
  {'Date': new Date(2018, 3, 09), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April09').modal('show');}},
  {'Date': new Date(2018, 3, 07), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April07').modal('show');}},
  {'Date': new Date(2018, 3, 06), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April06').modal('show');}},
  {'Date': new Date(2018, 3, 05), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April05').modal('show');}},
  {'Date': new Date(2018, 3, 04), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April04').modal('show');}},
  {'Date': new Date(2018, 3, 03), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April03').modal('show');}},
  {'Date': new Date(2018, 3, 02), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April02').modal('show');}},
  {'Date': new Date(2018, 3, 01), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018April01').modal('show');}},


  {'Date': new Date(2018, 2, 31), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March31').modal('show');}},
  {'Date': new Date(2018, 2, 30), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March30').modal('show');}},
  {'Date': new Date(2018, 2, 28), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March28').modal('show');}},
  {'Date': new Date(2018, 2, 26), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March26').modal('show');}},
  {'Date': new Date(2018, 2, 25), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March25').modal('show');}},
  {'Date': new Date(2018, 2, 24), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March24').modal('show');}},
  {'Date': new Date(2018, 2, 23), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March23').modal('show');}},
  {'Date': new Date(2018, 2, 22), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March22').modal('show');}},
  {'Date': new Date(2018, 2, 21), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March21').modal('show');}},
  {'Date': new Date(2018, 2, 20), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March20').modal('show');}},
  {'Date': new Date(2018, 2, 19), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March19').modal('show');}},
  {'Date': new Date(2018, 2, 18), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March18').modal('show');}},
  {'Date': new Date(2018, 2, 17), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March17').modal('show');}},
  {'Date': new Date(2018, 2, 16), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March16').modal('show');}},
  {'Date': new Date(2018, 2, 14), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March14').modal('show');}},
  {'Date': new Date(2018, 2, 13), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March13').modal('show');}},
  {'Date': new Date(2018, 2, 11), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March11').modal('show');}},
  {'Date': new Date(2018, 2, 10), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March10').modal('show');}},
  {'Date': new Date(2018, 2, 06), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March06').modal('show');}},
  {'Date': new Date(2018, 2, 05), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March05').modal('show');}},
  {'Date': new Date(2018, 2, 04), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March04').modal('show');}},
  {'Date': new Date(2018, 2, 03), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March03').modal('show');}},
  {'Date': new Date(2018, 2, 02), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March02').modal('show');}},
  {'Date': new Date(2018, 2, 01), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018March01').modal('show');}},

  {'Date': new Date(2018, 1, 28), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb28').modal('show');}},
  {'Date': new Date(2018, 1, 27), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb27').modal('show');}},
  {'Date': new Date(2018, 1, 26), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb26').modal('show');}},
  {'Date': new Date(2018, 1, 25), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb25').modal('show');}},
  {'Date': new Date(2018, 1, 24), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb24').modal('show');}},
  {'Date': new Date(2018, 1, 23), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb23').modal('show');}},
  {'Date': new Date(2018, 1, 21), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb21').modal('show');}},
  {'Date': new Date(2018, 1, 20), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb20').modal('show');}},
  {'Date': new Date(2018, 1, 19), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb19').modal('show');}},
  {'Date': new Date(2018, 1, 18), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb18').modal('show');}},
  {'Date': new Date(2018, 1, 17), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb17').modal('show');}},
  {'Date': new Date(2018, 1, 16), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb16').modal('show');}},
  {'Date': new Date(2018, 1, 15), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb15').modal('show');}},
  {'Date': new Date(2018, 1, 14), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb14').modal('show');}},
  {'Date': new Date(2018, 1, 13), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb13').modal('show');}},
  {'Date': new Date(2018, 1, 12), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb12').modal('show');}},
  {'Date': new Date(2018, 1, 11), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb11').modal('show');}},
  {'Date': new Date(2018, 1, 10), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb10').modal('show');}},
  {'Date': new Date(2018, 1, 09), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb09').modal('show');}},
  {'Date': new Date(2018, 1, 08), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb08').modal('show');}},
  {'Date': new Date(2018, 1, 07), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb07').modal('show');}},
  {'Date': new Date(2018, 1, 06), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb06').modal('show');}},
  {'Date': new Date(2018, 1, 05), 'Title': 'Alert status and activities of Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb05').modal('show');}},
  {'Date': new Date(2018, 1, 04), 'Title': 'Alert status and activities of Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb04').modal('show');}},
  {'Date': new Date(2018, 1, 03), 'Title': 'Alert status and activities of Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb03').modal('show');}},
  {'Date': new Date(2018, 1, 02), 'Title': 'Alert status and activities of Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb02').modal('show');}},
  {'Date': new Date(2018, 1, 01), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Feb01').modal('show');}},

 
  {'Date': new Date(2018, 0, 31), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan31').modal('show');}},
  {'Date': new Date(2018, 0, 30), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan30').modal('show');}},
  {'Date': new Date(2018, 0, 29), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan29').modal('show');}},
  {'Date': new Date(2018, 0, 27), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan27').modal('show');}},
  {'Date': new Date(2018, 0, 26), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan26').modal('show');}},
  {'Date': new Date(2018, 0, 24), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan24').modal('show');}},
  {'Date': new Date(2018, 0, 23), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan23').modal('show');}},
  {'Date': new Date(2018, 0, 22), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan22').modal('show');}},
  {'Date': new Date(2018, 0, 21), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan21').modal('show');}},
  {'Date': new Date(2018, 0, 20), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan20').modal('show');}},
  {'Date': new Date(2018, 0, 19), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan19').modal('show');}},
  {'Date': new Date(2018, 0, 18), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan18').modal('show');}},
  {'Date': new Date(2018, 0, 17), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan17').modal('show');}},
  {'Date': new Date(2018, 0, 15), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan15').modal('show');}},
  {'Date': new Date(2018, 0, 14), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan14').modal('show');}},
  {'Date': new Date(2018, 0, 13), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan13').modal('show');}},
  {'Date': new Date(2018, 0, 12), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan12').modal('show');}},
  {'Date': new Date(2018, 0, 10), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan10').modal('show');}},
  {'Date': new Date(2018, 0, 07), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan07').modal('show');}},
  {'Date': new Date(2018, 0, 06), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan06').modal('show');}},
  {'Date': new Date(2018, 0, 05), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan05').modal('show');}},
  {'Date': new Date(2018, 0, 04), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan04').modal('show');}},
  {'Date': new Date(2018, 0, 02), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan02').modal('show');}},
  {'Date': new Date(2018, 0, 01), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#2018Jan01').modal('show');}},


  {'Date': new Date(2017, 11, 31), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#Dec31').modal('show');}},
  {'Date': new Date(2017, 11, 29), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#Dec31').modal('show');}},
  {'Date': new Date(2017, 11, 28), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#Dec31').modal('show');}},
  {'Date': new Date(2017, 11, 27), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#Dec31').modal('show');}},
  {'Date': new Date(2017, 11, 26), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#Dec31').modal('show');}},
  {'Date': new Date(2017, 11, 25), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#Dec31').modal('show');}},
  {'Date': new Date(2017, 11, 24), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#Dec31').modal('show');}},
  {'Date': new Date(2017, 11, 21), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#Dec31').modal('show');}},
  {'Date': new Date(2017, 11, 23), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#Dec31').modal('show');}},
  {'Date': new Date(2017, 11, 20), 'Title': 'Alert status and activities of Mayon, Bulusan and Kanlaon Volcanoes', 'Link': function(){$('#Dec31').modal('show');}},








  {'Date': new Date(2018, 5, 22), 'Title': '', 'Link': ''},

];
var settings = {};
var element = document.getElementById('caleandar');
caleandar(element, events, settings);